baseurl: ""

repo: "https://github.com/T-INFORMATICA/DumbSchool"
github_user: "T-INFORMATICA"
github_repo: "t-informatica.github.io/DumbSchool"



collections:
    projects:
        output: true

defaults:
    - scope:
          path: "_projects"
      values:
          banner: "assets/images/woods.jpg"
          excerpt_separator: "<!--more-->"
          layout: "project"
    - scope:
          path: "_posts"
      values:
          banner: "assets/images/woods.jpg"
          excerpt_separator: "<!--more-->"
          layout: "blogpost"
    - scope:
          path: ""
      values:
          layout: "mainpage"

exclude:
    - "*.script.md"