baseurl: ""

repo: "https://github.com/teacher-svb/blog-example"
github_user: "teacher-svb"
github_repo: "https://teacher-svb.github.io/blog-example/"



collections:
    projects:
        output: true

defaults:
    - scope:
          path: "_projects"
      values:
          banner: "/blog-example/assets/images/woods.jpg"
          excerpt_separator: "<!--more-->"
          layout: "project"
    - scope:
          path: "_posts"
      values:
          banner: "/blog-example/assets/images/woods.jpg"
          excerpt_separator: "<!--more-->"
          layout: "blogpost"
    - scope:
          path: ""
      values:
          layout: "mainpage"

exclude:
    - "*.script.md"